import { defineAsyncComponent, type Component } from 'vue'

export interface DemoMeta {
  slug: string
  title: string
  description: string
  tags: string[]
  /** Primary library, used as a colour accent in the gallery. */
  lib: 'anime.js' | 'Lottie' | 'KUTE.js'
  component: Component
}

export const demos: DemoMeta[] = [
  {
    slug: 'line-drawing',
    title: 'Line drawing',
    description:
      'Self-drawing strokes via stroke-dash interpolation, staggered per path.',
    tags: ['createDrawable', 'stagger'],
    lib: 'anime.js',
    component: defineAsyncComponent(() => import('@/demos/LineDrawDemo.vue')),
  },
  {
    slug: 'shape-morphing',
    title: 'Shape morphing',
    description:
      "Interpolate one path's outline into another, even across different point counts.",
    tags: ['morphTo', 'path d'],
    lib: 'anime.js',
    component: defineAsyncComponent(() => import('@/demos/MorphDemo.vue')),
  },
  {
    slug: 'morph-loop',
    title: 'Morph loop',
    description: 'A looping timeline chains morphTo across four shapes, hands-free.',
    tags: ['timeline', 'morphTo'],
    lib: 'anime.js',
    component: defineAsyncComponent(() => import('@/demos/MorphLoopDemo.vue')),
  },
  {
    slug: 'grid-stagger',
    title: 'Grid stagger',
    description:
      'One call animates 88 nodes; the grid stagger ripples delay from an origin.',
    tags: ['stagger', 'grid'],
    lib: 'anime.js',
    component: defineAsyncComponent(() => import('@/demos/StaggerGridDemo.vue')),
  },
  {
    slug: 'motion-path',
    title: 'Motion path',
    description:
      'An element rides an SVG path, auto-rotating to follow the curve tangent.',
    tags: ['getPointAtLength', 'tangent'],
    lib: 'anime.js',
    component: defineAsyncComponent(() => import('@/demos/MotionPathDemo.vue')),
  },
  {
    slug: 'success-check',
    title: 'Success check',
    description: 'A timeline draws the ring, then the checkmark — a confirmation beat.',
    tags: ['timeline', 'createDrawable'],
    lib: 'anime.js',
    component: defineAsyncComponent(() => import('@/demos/CheckmarkDemo.vue')),
  },
  {
    slug: 'count-up',
    title: 'Count up',
    description:
      'A scalar tween drives a label via onUpdate while a drawable arc fills to match.',
    tags: ['onUpdate', 'createDrawable'],
    lib: 'anime.js',
    component: defineAsyncComponent(() => import('@/demos/CountUpDemo.vue')),
  },
  {
    slug: 'equalizer',
    title: 'Equalizer',
    description:
      "A center-out stagger animates each bar's height on an alternating loop.",
    tags: ['attributes', 'stagger'],
    lib: 'anime.js',
    component: defineAsyncComponent(() => import('@/demos/EqualizerDemo.vue')),
  },
  {
    slug: 'pulse-loader',
    title: 'Pulse loader',
    description: 'A staggered loop sends a highlight chasing around a ring of dots.',
    tags: ['stagger', 'loop'],
    lib: 'anime.js',
    component: defineAsyncComponent(() => import('@/demos/PulseLoaderDemo.vue')),
  },
  {
    slug: 'easing-lab',
    title: 'Easing lab',
    description: 'The same tween under six easings, side by side — compare how each curve moves.',
    tags: ['easings', 'compare'],
    lib: 'anime.js',
    component: defineAsyncComponent(() => import('@/demos/EasingLabDemo.vue')),
  },
  {
    slug: 'heartbeat',
    title: 'Heartbeat',
    description: 'A self-drawing ECG trace on an endless loop, with a pulse dot on the draw head.',
    tags: ['createDrawable', 'loop'],
    lib: 'anime.js',
    component: defineAsyncComponent(() => import('@/demos/HeartbeatDemo.vue')),
  },
  {
    slug: 'live-clock',
    title: 'Live clock',
    description: 'A real-time analog clock — one anime loop ticks per frame; the hands read the system clock.',
    tags: ['onUpdate', 'transform'],
    lib: 'anime.js',
    component: defineAsyncComponent(() => import('@/demos/ClockDemo.vue')),
  },
  {
    slug: 'pendulum',
    title: 'Pendulum',
    description: 'A plain angle tween drives an SVG rotate() about a fixed hinge; inOutSine gives a natural swing.',
    tags: ['onUpdate', 'inOutSine'],
    lib: 'anime.js',
    component: defineAsyncComponent(() => import('@/demos/PendulumDemo.vue')),
  },
  {
    slug: 'radial-burst',
    title: 'Radial burst',
    description: 'A looping progress tween radiates every spark outward on its own phase — a continuous emitter.',
    tags: ['onUpdate', 'loop'],
    lib: 'anime.js',
    component: defineAsyncComponent(() => import('@/demos/BurstDemo.vue')),
  },
  {
    slug: 'spring-physics',
    title: 'Spring physics',
    description: 'createSpring drives each marker — same distance, three stiffness/damping profiles, three settles.',
    tags: ['createSpring', 'physics'],
    lib: 'anime.js',
    component: defineAsyncComponent(() => import('@/demos/SpringDemo.vue')),
  },
  {
    slug: 'kute-morph',
    title: 'Path morph',
    description:
      "KUTE's cubic-morph plugin tweens one path outline into another, across differing point counts.",
    tags: ['path', 'morph'],
    lib: 'KUTE.js',
    component: defineAsyncComponent(() => import('@/demos/KuteMorphDemo.vue')),
  },
  {
    slug: 'kute-draw',
    title: 'Stroke draw',
    description:
      "KUTE's draw plugin measures the path and animates stroke-dashoffset to self-draw the stroke.",
    tags: ['draw', 'stroke'],
    lib: 'KUTE.js',
    component: defineAsyncComponent(() => import('@/demos/KuteDrawDemo.vue')),
  },
  {
    slug: 'kute-transform',
    title: 'SVG transform',
    description:
      'Rotate and scale an SVG group about a bbox-relative origin in a single transform attribute.',
    tags: ['svgTransform', 'origin'],
    lib: 'KUTE.js',
    component: defineAsyncComponent(() => import('@/demos/KuteTransformDemo.vue')),
  },
  {
    slug: 'kute-morph-chain',
    title: 'Morph sequence',
    description:
      "Four shapes on a loop — each tween's onComplete kicks off the next hop, since KUTE has no timeline.",
    tags: ['path', 'onComplete'],
    lib: 'KUTE.js',
    component: defineAsyncComponent(() => import('@/demos/KuteMorphChainDemo.vue')),
  },
  {
    slug: 'kute-attr',
    title: 'Attribute tween',
    description:
      'Animate raw SVG attributes — geometry and colour together, as a square becomes a rounded pill.',
    tags: ['attr', 'color'],
    lib: 'KUTE.js',
    component: defineAsyncComponent(() => import('@/demos/KuteAttrDemo.vue')),
  },
  {
    slug: 'kute-wave',
    title: 'Collection stagger',
    description:
      "One allFromTo call animates every dot; KUTE's offset option cascades the delay into a rolling wave.",
    tags: ['allFromTo', 'offset'],
    lib: 'KUTE.js',
    component: defineAsyncComponent(() => import('@/demos/KuteWaveDemo.vue')),
  },
  {
    slug: 'kute-counter',
    title: 'Number counter',
    description: "The textWrite plugin's number property rewrites the element text each frame — an eased count.",
    tags: ['number', 'textWrite'],
    lib: 'KUTE.js',
    component: defineAsyncComponent(() => import('@/demos/KuteCounterDemo.vue')),
  },
  {
    slug: 'kute-typewriter',
    title: 'Typewriter',
    description: "KUTE's text property scrambles one string into another — a decode-to-reveal typing effect.",
    tags: ['text', 'textWrite'],
    lib: 'KUTE.js',
    component: defineAsyncComponent(() => import('@/demos/KuteTypewriterDemo.vue')),
  },
  {
    slug: 'kute-easing',
    title: 'Easing lab',
    description: "KUTE's CubicBezier easing set — the same tween under six curves, side by side.",
    tags: ['easing', 'attr'],
    lib: 'KUTE.js',
    component: defineAsyncComponent(() => import('@/demos/KuteEasingDemo.vue')),
  },
  {
    slug: 'kute-flip',
    title: 'CSS 3D flip',
    description: 'KUTE animates CSS transforms too — a rotateY flip on a div, with perspective for real depth.',
    tags: ['transform', 'rotateY'],
    lib: 'KUTE.js',
    component: defineAsyncComponent(() => import('@/demos/KuteFlipDemo.vue')),
  },
  {
    slug: 'kute-pendulum',
    title: 'Pendulum',
    description: 'svgTransform with a top-edge transformOrigin (50% 0%) swings the arm from its hinge.',
    tags: ['svgTransform', 'origin'],
    lib: 'KUTE.js',
    component: defineAsyncComponent(() => import('@/demos/KutePendulumDemo.vue')),
  },
  {
    slug: 'kute-skew',
    title: 'Skew wobble',
    description: 'Rocking skewX about the base gives an SVG group a jelly-like wobble.',
    tags: ['svgTransform', 'skewX'],
    lib: 'KUTE.js',
    component: defineAsyncComponent(() => import('@/demos/KuteSkewDemo.vue')),
  },
  {
    slug: 'kute-color',
    title: 'Colour tween',
    description: 'The attr plugin interpolates fill and stroke in RGB — the blob warms as its outline cools.',
    tags: ['attr', 'colour'],
    lib: 'KUTE.js',
    component: defineAsyncComponent(() => import('@/demos/KuteColorDemo.vue')),
  },
  {
    slug: 'kute-cascade',
    title: 'Fade cascade',
    description: 'One allFromTo call fades a grid; the offset option ripples the reveal across in reading order.',
    tags: ['allFromTo', 'offset'],
    lib: 'KUTE.js',
    component: defineAsyncComponent(() => import('@/demos/KuteCascadeDemo.vue')),
  },
  {
    slug: 'kute-loader',
    title: 'Loader spin',
    description: 'A continuous svgTransform rotation (repeat, no yoyo, linear) spins a graded ring of dots.',
    tags: ['svgTransform', 'loop'],
    lib: 'KUTE.js',
    component: defineAsyncComponent(() => import('@/demos/KuteLoaderDemo.vue')),
  },
  {
    slug: 'lottie-playback',
    title: 'Lottie playback',
    description:
      'A designer-authored animation rendered to live SVG with runtime controls.',
    tags: ['lottie-web', 'animationData'],
    lib: 'Lottie',
    component: defineAsyncComponent(() => import('@/demos/LottieDemo.vue')),
  },
  {
    slug: 'lottie-scrubber',
    title: 'Lottie scrubber',
    description: 'Drive a Lottie by frame with a slider mapped straight to goToAndStop.',
    tags: ['lottie-web', 'goToAndStop', 'scrub'],
    lib: 'Lottie',
    component: defineAsyncComponent(() => import('@/demos/LottieScrubDemo.vue')),
  },
  {
    slug: 'lottie-hover',
    title: 'Hover to play',
    description: 'Pointer-driven Lottie — hover runs it forward, leaving reverses via setDirection.',
    tags: ['lottie-web', 'setDirection', 'interactive'],
    lib: 'Lottie',
    component: defineAsyncComponent(() => import('@/demos/LottieHoverDemo.vue')),
  },
  {
    slug: 'lottie-segments',
    title: 'Lottie segments',
    description: 'Play just part of the timeline — each button fires a frame range with playSegments.',
    tags: ['lottie-web', 'playSegments', 'timeline'],
    lib: 'Lottie',
    component: defineAsyncComponent(() => import('@/demos/LottieSegmentsDemo.vue')),
  },
  {
    slug: 'lottie-progress',
    title: 'Frame readout',
    description: 'The enterFrame event fires each rendered frame; here it feeds a live progress bar and counter.',
    tags: ['lottie-web', 'enterFrame', 'progress'],
    lib: 'Lottie',
    component: defineAsyncComponent(() => import('@/demos/LottieProgressDemo.vue')),
  },
  {
    slug: 'lottie-pingpong',
    title: 'Ping-pong loop',
    description: 'loop:false makes the complete event fire; flipping setDirection each boundary yields an endless there-and-back.',
    tags: ['lottie-web', 'complete', 'setDirection'],
    lib: 'Lottie',
    component: defineAsyncComponent(() => import('@/demos/LottiePingPongDemo.vue')),
  },
  {
    slug: 'lottie-speed',
    title: 'Speed compare',
    description: 'The same clip in three players — setSpeed runs them at 0.5×, 1× and 2× so the tempo difference is obvious.',
    tags: ['lottie-web', 'setSpeed', 'multi-instance'],
    lib: 'Lottie',
    component: defineAsyncComponent(() => import('@/demos/LottieSpeedDemo.vue')),
  },
  {
    slug: 'lottie-speed-dial',
    title: 'Speed dial',
    description: 'setSpeed is a live frame-rate multiplier — drag from a quarter speed up to 3× without touching the clip.',
    tags: ['lottie-web', 'setSpeed', 'slider'],
    lib: 'Lottie',
    component: defineAsyncComponent(() => import('@/demos/LottieSpeedSliderDemo.vue')),
  },
  {
    slug: 'lottie-loops',
    title: 'Loop counter',
    description: 'The loopComplete event fires each time the playhead wraps — here it tallies completed cycles.',
    tags: ['lottie-web', 'loopComplete', 'events'],
    lib: 'Lottie',
    component: defineAsyncComponent(() => import('@/demos/LottieLoopsDemo.vue')),
  },
  {
    slug: 'lottie-seg-loop',
    title: 'Segment loop',
    description: 'With loop:true, playSegments repeats just the chosen frame range forever — pick which slice cycles.',
    tags: ['lottie-web', 'playSegments', 'loop'],
    lib: 'Lottie',
    component: defineAsyncComponent(() => import('@/demos/LottieSegLoopDemo.vue')),
  },
  {
    slug: 'lottie-replay',
    title: 'Play once',
    description: 'A one-shot clip: complete fires at the end, and goToAndPlay(0) restarts it on demand.',
    tags: ['lottie-web', 'complete', 'goToAndPlay'],
    lib: 'Lottie',
    component: defineAsyncComponent(() => import('@/demos/LottieReplayDemo.vue')),
  },
  {
    slug: 'lottie-drag',
    title: 'Drag to scrub',
    description: "The pointer's x-position maps straight to goToAndStop — drag across the stage to scrub the timeline.",
    tags: ['lottie-web', 'goToAndStop', 'pointer'],
    lib: 'Lottie',
    component: defineAsyncComponent(() => import('@/demos/LottieDragDemo.vue')),
  },
  {
    slug: 'lottie-subframe',
    title: 'Subframe smoothing',
    description: 'setSubframe interpolates between integer frames; turn it off and the spin snaps frame-to-frame.',
    tags: ['lottie-web', 'setSubframe', 'render'],
    lib: 'Lottie',
    component: defineAsyncComponent(() => import('@/demos/LottieSubframeDemo.vue')),
  },
  {
    slug: 'lottie-direction',
    title: 'Direction',
    description: 'setDirection flips playback sign — the same spinner runs clockwise or counter-clockwise on demand.',
    tags: ['lottie-web', 'setDirection', 'playback'],
    lib: 'Lottie',
    component: defineAsyncComponent(() => import('@/demos/LottieDirectionDemo.vue')),
  },
  {
    slug: 'lottie-theme',
    title: 'Retint at runtime',
    description: 'One clip, three palettes — deep-clone the animationData and rewrite the fill colour array before loading.',
    tags: ['lottie-web', 'animationData', 'theming'],
    lib: 'Lottie',
    component: defineAsyncComponent(() => import('@/demos/LottieThemeDemo.vue')),
  },
]

export const demosBySlug = new Map(demos.map((d) => [d.slug, d]))
